# product_key: chef

slack:
  notify_channel: bot-testing

# docker:
#   dockerfile: Dockerfile
#   build_args:
#      CHANNEL: "{{channel}}"
#      VERSION: "{{version}}"
#   image_name: chef/chef
#   published_url: https://hub.docker.com/r/chef/chef/tags

github:
  version_bump_command: "bump_version.sh"
  version_show_command: "echo VERSION"
  # dependency_update_command: "ci/dependency_update.sh"
