# You can update the date below to force a refresh of the agent config.
# TRIGGER: Thu Jan 24 15:46:40 CST 2019
---
slack:
  notify_channel:
    - expeditor-testing
    - expeditor-priv:
        private: true

github:
  delete_branch_on_merge: true
  minor_bump_labels:
     - "Expeditor: Bump Minor Version"

pipelines:
  - omnibus/harmony-acceptance:
      env:
        - EXPEDITOR_CHANNEL: acceptance
  - public-test:
      organization: chef-oss
      description: An empty pipeline to test communication with Buildkite
      env:
        - EXPEDITOR_CHANNEL: acceptance
  - private-test:
      description: An empty pipelint to test communication with Buildkite
      env:
        - EXPEDITOR_CHANNEL: acceptance
