
# You can update the date below to force a refresh of the agent config.
# TRIGGER: Thu Jan 24 15:46:40 CST 2019
---
slack:
  notify_channel:
    - expeditor-testing
    - expeditor-priv:
        private: true

github:
  delete_branch_on_merge: true
  minor_bump_labels:
     - "Expeditor: Bump Minor Version"
