project:
  alias: expeditor-acceptance
  base_config:
    repo: chef-boneyard/expeditor-acceptance
    file: .expeditor/base_config.yml

pipelines:
  - new_cd_public:
      definition: .expeditor/new-cd-pipeline.pipeline.yml
      public: true
      env:
        - EXPEDITOR_CHANNEL: acceptance
  # - new_cd_private:
  #     definition: .expeditor/new-cd-pipeline.pipeline.yml
  #     env:
  #       - EXPEDITOR_CHANNEL: acceptance
  - omnibus/harmony-acceptance:
      env:
        - EXPEDITOR_CHANNEL: acceptance

habitat_packages:
  - expeditor-acceptance-empty:
      origin: chef-es

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
  - built_in:trigger_habitat_package_build
  - trigger_pipeline:omnibus/harmony-acceptance

subscriptions:
  - workload: generic_workload_published:acceptance_tests:*
    actions:
      - bash:.expeditor/trigger_pr_merge_tests.sh

