base_config:
  file: .expeditor/base_config.yml

project:
  alias: expeditor-acceptance
  
staging_areas:
  - demo:
      workload: generic_workload_published:*
      timeout: 2m

pipelines:
  - verify:
      public: true
  - new_cd_public:
      definition: .expeditor/new-cd-pipeline.pipeline.yml
      public: true
  - omnibus/harmony-acceptance:
      # do not use canary buildkite org to test omnibus pipelines because many platforms don't run canary buildkite agents
      env:
        - ADHOC: true
  - docker/build:
      canary: true
      env:
        - DOBI_S3_BUCKET_NAME: "docker-buildkite-cache-chef-canary-canary"
  - habitat/build:
      canary: true

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - create_github_issue:.expeditor/templates/pr_merge.mustache
      - built_in:bump_version:
          ignore_labels:
            - "Version: Skip Bump"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Changelog: Skip Update"
      - trigger_pipeline:habitat/build
      - trigger_pipeline:docker/build
      - trigger_pipeline:omnibus/harmony-acceptance
  - workload: generic_workload_published:acceptance_tests:*
    actions:
      - bash:.expeditor/trigger_pr_merge_tests.sh
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
  # - workload: project_promoted:{{agent_id}}:*
  #   delay: 30m
  #   actions:
  #     - built_in:promote_docker_images
  - workload: project_promoted:{{agent_id}}:*
    pull_request:
      title: "{{event}}:{{name}}"
      description: .expeditor/templates/promoted.mustache
      branch: "expeditor/test-{{event}}-stache"
    actions:
      - bash:.expeditor/songs.sh
