slack:
  notify_channel: bot-testing

# docker:
#   dockerfile: Dockerfile
#   build_args:
#      CHANNEL: "{{channel}}"
#      VERSION: "{{version}}"
#   image_name: chef/chef
#   published_url: https://hub.docker.com/r/chef/chef/tags

github:
  bump_version: true
